version: '3.8'
services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend