# Generated by Django 5.2.3 on 2025-06-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutesAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordfrequency',
            name='unique_word_per_date',
        ),
        migrations.AlterUniqueTogether(
            name='wordfrequency',
            unique_together={('date', 'word')},
        ),
    ]
