# Generated by Django 5.2.1 on 2025-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('other', 'Other')], default='other', max_length=20)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('other_description', models.CharField(blank=True, default='', max_length=255)),
                ('purpose_of_contact', models.CharField(blank=True, choices=[('general_inquiry', 'General Inquiry'), ('collaboration', 'Collaboration'), ('job_opportunity', 'Job Opportunity'), ('other', 'Other')], default='other', max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(choices=[('paper', 'Research Paper'), ('dataset', 'Dataset'), ('code', 'Code Repository')], max_length=20)),
                ('resource_slug', models.SlugField(help_text='Unique slug identifying the item', max_length=100)),
                ('resource_name', models.CharField(help_text='Human-readable name of the item', max_length=255)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
