# Generated by Django 5.2.1 on 2025-06-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcVoting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dissentyear',
            options={'ordering': ['year'], 'verbose_name': 'Dissent Year', 'verbose_name_plural': 'Dissent Years'},
        ),
        migrations.AlterModelOptions(
            name='membervoting',
            options={'ordering': ['name'], 'verbose_name': 'Member Voting Record', 'verbose_name_plural': 'Member Voting Records'},
        ),
        migrations.AddField(
            model_name='membervoting',
            name='tenure',
            field=models.CharField(blank=True, help_text="Member's tenure period (e.g., 'Oct 2020 - Oct 2024')", max_length=100, null=True),
        ),
    ]
