# Generated by Django 5.2.1 on 2025-05-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='institute_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='purpose_of_contact',
            field=models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('collaboration', 'Collaboration'), ('job_opportunity', 'Job Opportunity'), ('other', 'Other')], default='general_inquiry', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
