# Generated by Django 5.2.1 on 2025-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactsubmission_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='institute_name',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='other_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='purpose_of_contact',
            field=models.CharField(blank=True, choices=[('general_inquiry', 'General Inquiry'), ('collaboration', 'Collaboration'), ('job_opportunity', 'Job Opportunity'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
