# Generated by Django 5.2.1 on 2025-05-31 14:23

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('paper', 'Research Paper'), ('dataset', 'Dataset'), ('code', 'Code Repository')], default='paper', max_length=20)),
                ('slug', models.SlugField(help_text="Unique slug for this resource (e.g. 'impact-monetary-policy-inflation')", max_length=100, unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload a thumbnail image (JPG, PNG).', null=True, upload_to=resources.models.upload_to_thumbnail)),
                ('file', models.FileField(blank=True, help_text='Upload the downloadable file (PDF, CSV, XLSX, etc.).', null=True, upload_to=resources.models.upload_to_file)),
                ('external_url', models.URLField(blank=True, help_text='Optional: external URL (e.g. GitHub repo). If provided, file field can be blank.', max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resource Item',
                'verbose_name_plural': 'Resource Items',
                'ordering': ['-created_on'],
            },
        ),
    ]
