# Generated by Django 5.2.1 on 2025-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('research', 'Research Team'), ('collaborator', 'Collaborators')], default='research', max_length=20),
        ),
    ]
