# Generated by Django 5.2.1 on 2025-05-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_bio_teammember_area_of_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='profile_url',
            new_name='profileUrl',
        ),
    ]
